/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BpfJava */

#ifndef _Included_BpfJava
#define _Included_BpfJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BpfJava
 * Method:    validate
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_BpfJava_validate
  (JNIEnv *, jobject, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
